package com.github.mihomo.android.ui.theme

import androidx.compose.runtime.Composable
import androidx.compose.runtime.compositionLocalOf
import java.util.Locale

val LocalAppLanguage = compositionLocalOf { "SYSTEM" }

object AppStrings {
    private val zh = mapOf(
        "nav_dashboard" to "仪表",
        "nav_proxies" to "策略",
        "nav_profiles" to "配置",
        "nav_settings" to "设置",
        "mode_rule" to "规则模式",
        "mode_global" to "全局模式",
        "mode_direct" to "直连模式",
        "select_mode" to "选择运行模式",
        "traffic_up" to "上传",
        "traffic_down" to "下载",
        "shortcuts" to "快捷方式",
        "shortcuts_edit" to "编辑",
        "shortcuts_done" to "完成",
        "shortcuts_add" to "添加快捷方式",
        "shortcuts_all_added" to "所有快捷方式已添加到首页",
        "shortcuts_all_shown" to "已显示所有快捷方式",
        "shortcut_nodes" to "节点",
        "shortcut_profiles" to "配置文件",
        "shortcut_logs" to "核心日志",
        "shortcut_requests" to "请求记录",
        "shortcut_dns" to "DNS 记录",
        "shortcut_rules" to "规则",
        "shortcut_routing" to "分应用代理",
        "shortcut_plugins" to "内核信息",
        "shortcut_network_share" to "网络共享",
        "proxies_title" to "策略与节点",
        "proxies_view_tabs" to "标签模式",
        "proxies_view_list" to "列表模式",
        "proxies_test" to "测速",
        "proxies_timeout" to "超时",
        "quick_node_title" to "出站节点快速选择",
        "search_nodes" to "搜索节点...",
        "no_nodes_available" to "当前无可用节点",
        "no_nodes_matched" to "未匹配到节点",
        "profiles_title" to "配置管理",
        "profiles_add" to "添加配置",
        "profiles_empty" to "暂无订阅配置，点击右上角添加",
        "profile_override" to "覆写",
        "profile_edit" to "编辑",
        "profile_update" to "更新",
        "profile_delete" to "删除",
        "settings_title" to "设置",
        "settings_core_service" to "核心与服务",
        "settings_general" to "通用与外观",
        "settings_tun_stack" to "TUN 堆栈模式",
        "settings_boot_startup" to "开机自启动",
        "settings_theme" to "外观主题",
        "settings_language" to "界面语言",
        "settings_scripts" to "脚本管理",
        "settings_routing_section" to "分流与规则",
        "settings_app_routing" to "分应用代理",
        "settings_lan_share" to "局域网共享 (7890)",
        "settings_profiles_subs" to "配置文件与订阅",
        "settings_dns_section" to "DNS 设置",
        "settings_fakeip" to "Fake-IP 增强模式",
        "settings_upstream_dns" to "上游服务器",
        "settings_core_section" to "内核与系统日志",
        "settings_realtime_log" to "核心实时日志",
        "settings_log_level" to "内核日志等级",
        "settings_core_version" to "内核版本",
        "settings_arch" to "系统架构",
        "settings_reset_core" to "重置内核状态",
        "settings_always_on_vpn" to "始终开启的 VPN (系统设置)",
        "settings_view_stream" to "查看流",
        "settings_about" to "关于 Nexus",
        "theme_system" to "跟随系统",
        "theme_light" to "浅色模式",
        "theme_dark" to "深色模式",
        "confirm" to "确定",
        "cancel" to "取消",
        "dialog_ok" to "知道了",
        "language_updated" to "语言设置已更新"
    )

    private val en = mapOf(
        "nav_dashboard" to "Dashboard",
        "nav_proxies" to "Proxies",
        "nav_profiles" to "Profiles",
        "nav_settings" to "Settings",
        "mode_rule" to "Rule Mode",
        "mode_global" to "Global Mode",
        "mode_direct" to "Direct Mode",
        "select_mode" to "Select Tunnel Mode",
        "traffic_up" to "Upload",
        "traffic_down" to "Download",
        "shortcuts" to "Shortcuts",
        "shortcuts_edit" to "Edit",
        "shortcuts_done" to "Done",
        "shortcuts_add" to "Add Shortcut",
        "shortcuts_all_added" to "All shortcuts added to dashboard",
        "shortcuts_all_shown" to "All shortcuts visible",
        "shortcut_nodes" to "Nodes",
        "shortcut_profiles" to "Profiles",
        "shortcut_logs" to "Core Logs",
        "shortcut_requests" to "Requests",
        "shortcut_dns" to "DNS Records",
        "shortcut_rules" to "Rules",
        "shortcut_routing" to "App Routing",
        "shortcut_plugins" to "Core Info",
        "shortcut_network_share" to "Network Share",
        "proxies_title" to "Proxies & Groups",
        "proxies_view_tabs" to "Tabs",
        "proxies_view_list" to "List",
        "proxies_test" to "Speed Test",
        "proxies_timeout" to "Timeout",
        "quick_node_title" to "Quick Node Selector",
        "search_nodes" to "Search nodes...",
        "no_nodes_available" to "No proxies available",
        "no_nodes_matched" to "No matching nodes found",
        "profiles_title" to "Profile Manager",
        "profiles_add" to "Add Profile",
        "profiles_empty" to "No profiles found, tap + to add",
        "profile_override" to "Override",
        "profile_edit" to "Edit",
        "profile_update" to "Update",
        "profile_delete" to "Delete",
        "settings_title" to "Settings",
        "settings_core_service" to "Core & Network",
        "settings_general" to "General & Appearance",
        "settings_tun_stack" to "TUN Stack",
        "settings_boot_startup" to "Boot on Startup",
        "settings_theme" to "Theme Mode",
        "settings_language" to "Language",
        "settings_scripts" to "Scripts",
        "settings_about" to "About Nexus",
        "settings_routing_section" to "Routing & Rules",
        "settings_app_routing" to "Per-App Routing",
        "settings_lan_share" to "LAN Sharing (7890)",
        "settings_profiles_subs" to "Profiles & Subscriptions",
        "settings_dns_section" to "DNS Settings",
        "settings_fakeip" to "Fake-IP Enhanced Mode",
        "settings_upstream_dns" to "Upstream DNS",
        "settings_core_section" to "Core & Logs",
        "settings_realtime_log" to "Core Live Logs",
        "settings_log_level" to "Log Level",
        "settings_core_version" to "Core Version",
        "settings_arch" to "Architecture",
        "settings_reset_core" to "Reset Core State",
        "settings_always_on_vpn" to "Always-On VPN (System)",
        "settings_view_stream" to "View Stream",
        "theme_system" to "Follow System",
        "theme_light" to "Light",
        "theme_dark" to "Dark",
        "confirm" to "Confirm",
        "cancel" to "Cancel",
        "dialog_ok" to "Got it",
        "language_updated" to "Language updated"
    )

    private val ru = mapOf(
        "nav_dashboard" to "Панель",
        "nav_proxies" to "Прокси",
        "nav_profiles" to "Конфиги",
        "nav_settings" to "Настройки",
        "mode_rule" to "По правилам",
        "mode_global" to "Глобальный",
        "mode_direct" to "Прямой",
        "select_mode" to "Режим работы",
        "traffic_up" to "Отдача",
        "traffic_down" to "Загрузка",
        "shortcuts" to "Ярлыки",
        "shortcuts_edit" to "Изменить",
        "shortcuts_done" to "Готово",
        "shortcuts_add" to "Добавить ярлык",
        "shortcuts_all_added" to "Все ярлыки добавлены",
        "shortcuts_all_shown" to "Все ярлыки отображаются",
        "shortcut_nodes" to "Узлы",
        "shortcut_profiles" to "Конфигурация",
        "shortcut_logs" to "Логи ядра",
        "shortcut_requests" to "Запросы",
        "shortcut_dns" to "DNS Записи",
        "shortcut_rules" to "Правила",
        "shortcut_routing" to "Маршрутизация",
        "shortcut_plugins" to "Инфо о ядре",
        "shortcut_network_share" to "Общий доступ",
        "proxies_title" to "Прокси и группы",
        "proxies_view_tabs" to "Вкладки",
        "proxies_view_list" to "Список",
        "proxies_test" to "Тест скорости",
        "proxies_timeout" to "Таймаут",
        "quick_node_title" to "Быстрый выбор узла",
        "search_nodes" to "Поиск узлов...",
        "no_nodes_available" to "Нет доступных прокси",
        "no_nodes_matched" to "Узлы не найдены",
        "profiles_title" to "Управление конфигами",
        "profiles_add" to "Добавить конфиг",
        "profiles_empty" to "Нет конфигов, нажмите +",
        "profile_override" to "Переопределение",
        "profile_edit" to "Изменить",
        "profile_update" to "Обновить",
        "profile_delete" to "Удалить",
        "settings_title" to "Настройки",
        "settings_core_service" to "Ядро и сеть",
        "settings_general" to "Общие и тема",
        "settings_tun_stack" to "Стек TUN",
        "settings_boot_startup" to "Автозапуск",
        "settings_theme" to "Тема оформления",
        "settings_language" to "Язык интерфейса",
        "settings_scripts" to "Скрипты",
        "settings_about" to "О программе",
        "settings_routing_section" to "Маршрутизация и правила",
        "settings_app_routing" to "Маршрутизация приложений",
        "settings_lan_share" to "Доступ по LAN (7890)",
        "settings_profiles_subs" to "Конфиги и подписки",
        "settings_dns_section" to "Настройки DNS",
        "settings_fakeip" to "Режим Fake-IP",
        "settings_upstream_dns" to "Вышестоящий DNS",
        "settings_core_section" to "Ядро и логи",
        "settings_realtime_log" to "Логи ядра в реальном времени",
        "settings_log_level" to "Уровень логирования",
        "settings_core_version" to "Версия ядра",
        "settings_arch" to "Архитектура",
        "settings_reset_core" to "Сбросить ядро",
        "settings_always_on_vpn" to "Постоянный VPN (система)",
        "settings_view_stream" to "Просмотр потока",
        "theme_system" to "Как в системе",
        "theme_light" to "Светлая",
        "theme_dark" to "Темная",
        "confirm" to "ОК",
        "cancel" to "Отмена",
        "dialog_ok" to "Понятно",
        "language_updated" to "Язык обновлен"
    )

    fun get(key: String, languageCode: String = "SYSTEM"): String {
        val effectiveLang = if (languageCode == "SYSTEM") {
            val sys = Locale.getDefault().language
            if (sys == "zh" || sys == "ru") sys else "en"
        } else {
            languageCode
        }

        val dict = when (effectiveLang.lowercase()) {
            "zh" -> zh
            "ru" -> ru
            else -> en
        }

        return dict[key] ?: zh[key] ?: key
    }

    @Composable
    fun current(key: String): String {
        return get(key, LocalAppLanguage.current)
    }
}