package com.github.mihomo.android.ui.theme

import androidx.compose.runtime.Composable
import androidx.compose.runtime.compositionLocalOf
import java.util.Locale

val LocalAppLanguage = compositionLocalOf { "SYSTEM" }

object AppStrings {
    private val zh = mapOf(
        "nav_dashboard" to "仪表",
        "nav_proxies" to "策略",
        "nav_profiles" to "配置",
        "nav_settings" to "设置",
        "mode_rule" to "规则模式",
        "mode_global" to "全局模式",
        "mode_direct" to "直连模式",
        "select_mode" to "选择运行模式",
        "traffic_up" to "上传",
        "traffic_down" to "下载",
        "shortcuts" to "快捷方式",
        "shortcuts_edit" to "编辑",
        "shortcuts_done" to "完成",
        "shortcuts_add" to "添加快捷方式",
        "shortcuts_all_added" to "所有快捷方式已添加到首页",
        "shortcuts_all_shown" to "已显示所有快捷方式",
        "shortcut_nodes" to "节点",
        "shortcut_profiles" to "配置文件",
        "shortcut_logs" to "核心日志",
        "shortcut_requests" to "请求记录",
        "shortcut_dns" to "DNS 记录",
        "shortcut_rules" to "规则",
        "shortcut_routing" to "分应用代理",
        "shortcut_plugins" to "内核信息",
        "shortcut_network_share" to "网络共享",
        "proxies_title" to "策略与节点",
        "proxies_view_tabs" to "标签模式",
        "proxies_view_list" to "列表模式",
        "proxies_test" to "测速",
        "proxies_timeout" to "超时",
        "quick_node_title" to "出站节点快速选择",
        "search_nodes" to "搜索节点...",
        "no_nodes_available" to "当前无可用节点",
        "no_nodes_matched" to "未匹配到节点",
        "profiles_title" to "配置管理",
        "profiles_add" to "添加配置",
        "profiles_empty" to "暂无订阅配置，点击右上角添加",
        "profile_override" to "覆写",
        "profile_edit" to "编辑",
        "profile_update" to "更新",
        "profile_delete" to "删除",
        "settings_title" to "设置",
        "settings_core_service" to "核心与服务",
        "settings_general" to "通用与外观",
        "settings_tun_stack" to "TUN 堆栈模式",
        "settings_boot_startup" to "开机自启动",
        "settings_theme" to "外观主题",
        "settings_language" to "界面语言",
        "settings_scripts" to "脚本管理",
        "settings_routing_section" to "分流与规则",
        "settings_app_routing" to "分应用代理",
        "settings_lan_share" to "局域网共享 (7890)",
        "settings_profiles_subs" to "配置文件与订阅",
        "settings_dns_section" to "DNS 设置",
        "settings_fakeip" to "Fake-IP 增强模式",
        "settings_upstream_dns" to "上游服务器",
        "settings_core_section" to "内核与系统日志",
        "settings_realtime_log" to "核心实时日志",
        "settings_log_level" to "内核日志等级",
        "settings_core_version" to "内核版本",
        "settings_arch" to "系统架构",
        "settings_reset_core" to "重置内核状态",
        "settings_reset_core_confirm" to "确定要重置内核状态吗？当前连接会断开。",
        "settings_always_on_vpn" to "始终开启的 VPN (系统设置)",
        "settings_view_stream" to "查看流",
        "settings_about" to "关于 Nexus",
        "theme_system" to "跟随系统",
        "theme_light" to "浅色模式",
        "theme_dark" to "深色模式",
        "confirm" to "确定",
        "cancel" to "取消",
        "dialog_ok" to "知道了",
        "language_updated" to "语言设置已更新"
    )

    private val en = mapOf(
        "nav_dashboard" to "Dashboard",
        "nav_proxies" to "Proxies",
        "nav_profiles" to "Profiles",
        "nav_settings" to "Settings",
        "mode_rule" to "Rule Mode",
        "mode_global" to "Global Mode",
        "mode_direct" to "Direct Mode",
        "select_mode" to "Select Tunnel Mode",
        "traffic_up" to "Upload",
        "traffic_down" to "Download",
        "shortcuts" to "Shortcuts",
        "shortcuts_edit" to "Edit",
        "shortcuts_done" to "Done",
        "shortcuts_add" to "Add Shortcut",
        "shortcuts_all_added" to "All shortcuts added to dashboard",
        "shortcuts_all_shown" to "All shortcuts visible",
        "shortcut_nodes" to "Nodes",
        "shortcut_profiles" to "Profiles",
        "shortcut_logs" to "Core Logs",
        "shortcut_requests" to "Requests",
        "shortcut_dns" to "DNS Records",
        "shortcut_rules" to "Rules",
        "shortcut_routing" to "App Routing",
        "shortcut_plugins" to "Core Info",
        "shortcut_network_share" to "Network Share",
        "proxies_title" to "Proxies & Groups",
        "proxies_view_tabs" to "Tabs",
        "proxies_view_list" to "List",
        "proxies_test" to "Speed Test",
        "proxies_timeout" to "Timeout",
        "quick_node_title" to "Quick Node Selector",
        "search_nodes" to "Search nodes...",
        "no_nodes_available" to "No proxies available",
        "no_nodes_matched" to "No matching nodes found",
        "profiles_title" to "Profile Manager",
        "profiles_add" to "Add Profile",
        "profiles_empty" to "No profiles found, tap + to add",
        "profile_override" to "Override",
        "profile_edit" to "Edit",
        "profile_update" to "Update",
        "profile_delete" to "Delete",
        "settings_title" to "Settings",
        "settings_core_service" to "Core & Network",
        "settings_general" to "General & Appearance",
        "settings_tun_stack" to "TUN Stack",
        "settings_boot_startup" to "Boot on Startup",
        "settings_theme" to "Theme Mode",
        "settings_language" to "Language",
        "settings_scripts" to "Scripts",
        "settings_about" to "About Nexus",
        "settings_routing_section" to "Routing & Rules",
        "settings_app_routing" to "Per-App Routing",
        "settings_lan_share" to "LAN Sharing (7890)",
        "settings_profiles_subs" to "Profiles & Subscriptions",
        "settings_dns_section" to "DNS Settings",
        "settings_fakeip" to "Fake-IP Enhanced Mode",
        "settings_upstream_dns" to "Upstream DNS",
        "settings_core_section" to "Core & Logs",
        "settings_realtime_log" to "Core Live Logs",
        "settings_log_level" to "Log Level",
        "settings_core_version" to "Core Version",
        "settings_arch" to "Architecture",
        "settings_reset_core" to "Reset Core State",
        "settings_reset_core_confirm" to "Reset the core state? The current connection will be dropped.",
        "settings_always_on_vpn" to "Always-On VPN (System)",
        "settings_view_stream" to "View Stream",
        "theme_system" to "Follow System",
        "theme_light" to "Light",
        "theme_dark" to "Dark",
        "confirm" to "Confirm",
        "cancel" to "Cancel",
        "dialog_ok" to "Got it",
        "language_updated" to "Language updated"
    )

    private val ru = mapOf(
        "nav_dashboard" to "Панель",
        "nav_proxies" to "Прокси",
        "nav_profiles" to "Конфиги",
        "nav_settings" to "Настройки",
        "mode_rule" to "По правилам",
        "mode_global" to "Глобальный",
        "mode_direct" to "Прямой",
        "select_mode" to "Режим работы",
        "traffic_up" to "Отдача",
        "traffic_down" to "Загрузка",
        "shortcuts" to "Ярлыки",
        "shortcuts_edit" to "Изменить",
        "shortcuts_done" to "Готово",
        "shortcuts_add" to "Добавить ярлык",
        "shortcuts_all_added" to "Все ярлыки добавлены",
        "shortcuts_all_shown" to "Все ярлыки отображаются",
        "shortcut_nodes" to "Узлы",
        "shortcut_profiles" to "Конфигурация",
        "shortcut_logs" to "Логи ядра",
        "shortcut_requests" to "Запросы",
        "shortcut_dns" to "DNS Записи",
        "shortcut_rules" to "Правила",
        "shortcut_routing" to "Маршрутизация",
        "shortcut_plugins" to "Инфо о ядре",
        "shortcut_network_share" to "Общий доступ",
        "proxies_title" to "Прокси и группы",
        "proxies_view_tabs" to "Вкладки",
        "proxies_view_list" to "Список",
        "proxies_test" to "Тест скорости",
        "proxies_timeout" to "Таймаут",
        "quick_node_title" to "Быстрый выбор узла",
        "search_nodes" to "Поиск узлов...",
        "no_nodes_available" to "Нет доступных прокси",
        "no_nodes_matched" to "Узлы не найдены",
        "profiles_title" to "Управление конфигами",
        "profiles_add" to "Добавить конфиг",
        "profiles_empty" to "Нет конфигов, нажмите +",
        "profile_override" to "Переопределение",
        "profile_edit" to "Изменить",
        "profile_update" to "Обновить",
        "profile_delete" to "Удалить",
        "settings_title" to "Настройки",
        "settings_core_service" to "Ядро и сеть",
        "settings_general" to "Общие и тема",
        "settings_tun_stack" to "Стек TUN",
        "settings_boot_startup" to "Автозапуск",
        "settings_theme" to "Тема оформления",
        "settings_language" to "Язык интерфейса",
        "settings_scripts" to "Скрипты",
        "settings_about" to "О программе",
        "settings_routing_section" to "Маршрутизация и правила",
        "settings_app_routing" to "Маршрутизация приложений",
        "settings_lan_share" to "Доступ по LAN (7890)",
        "settings_profiles_subs" to "Конфиги и подписки",
        "settings_dns_section" to "Настройки DNS",
        "settings_fakeip" to "Режим Fake-IP",
        "settings_upstream_dns" to "Вышестоящий DNS",
        "settings_core_section" to "Ядро и логи",
        "settings_realtime_log" to "Логи ядра в реальном времени",
        "settings_log_level" to "Уровень логирования",
        "settings_core_version" to "Версия ядра",
        "settings_arch" to "Архитектура",
        "settings_reset_core" to "Сбросить ядро",
        "settings_reset_core_confirm" to "Сбросить состояние ядра? Текущее подключение будет разорвано.",
        "settings_always_on_vpn" to "Постоянный VPN (система)",
        "settings_view_stream" to "Просмотр потока",
        "theme_system" to "Как в системе",
        "theme_light" to "Светлая",
        "theme_dark" to "Темная",
        "confirm" to "ОК",
        "cancel" to "Отмена",
        "dialog_ok" to "Понятно",
        "language_updated" to "Язык обновлен"
    )

    // ---------------------------------------------------------------------
    // Strings for the screens that previously hardcoded Chinese text.
    // Kept as separate tables so the original dictionaries stay untouched.
    // `{n}`, `{name}`, `{msg}` are placeholders filled in by the call site.
    // ---------------------------------------------------------------------
    private val zhExtra = mapOf(
        "back" to "返回",
        "logs_title" to "核心实时日志",
        "logs_count" to "共 {n} 条记录",
        "logs_copied" to "日志已复制到剪贴板",
        "logs_copy" to "复制日志",
        "logs_export" to "导出日志",
        "logs_clear" to "清空日志",
        "logs_empty" to "暂无日志输出\n连接 VPN 后，Mihomo 内核实时输出将显示在此处",
        "log_level_all" to "全部",
        "log_level_info" to "信息",
        "log_level_warning" to "警告",
        "log_level_error" to "错误",
        "log_level_debug" to "调试",
        "app_routing_title" to "分应用代理",
        "per_app_disabled" to "关闭",
        "per_app_whitelist" to "仅代理选中",
        "per_app_blacklist" to "绕过选中",
        "app_search_placeholder" to "搜索应用名称或包名…",
        "app_selected_count" to "已选 {n} 个应用",
        "app_show_system" to "显示系统应用",
        "app_proxied_section" to "已代理应用 ({n})",
        "app_unproxied_section" to "未代理应用 ({n})",
        "app_no_match" to "没有找到匹配的应用",
        "app_routing_disabled_hint" to "分应用代理已关闭\n所有应用网络均经由 Mihomo 规则分流",
        "scripts_title" to "脚本",
        "scripts_import_network" to "网络导入",
        "scripts_import_local" to "本地导入",
        "scripts_new" to "新建脚本",
        "scripts_empty" to "暂无 JS 复写脚本\n点击上方按钮导入或新建脚本",
        "scripts_bind_hint" to "在配置覆写中绑定生效",
        "scripts_edit" to "编辑",
        "scripts_new_title" to "新建配置脚本",
        "scripts_name_label" to "脚本名称",
        "scripts_name_placeholder" to "例如：Clash_rule",
        "scripts_created" to "脚本创建成功",
        "scripts_create" to "创建",
        "scripts_import_url_title" to "从网络链接导入脚本",
        "scripts_name_optional" to "脚本名称（选填）",
        "scripts_url_label" to "脚本 URL",
        "scripts_downloaded" to "脚本下载成功",
        "scripts_download_failed" to "下载失败: {msg}",
        "scripts_downloading" to "正在下载…",
        "scripts_import" to "导入",
        "scripts_edit_title" to "编辑: {name}",
        "scripts_saved" to "脚本已保存",
        "scripts_save_code" to "保存代码",
        "scripts_delete_title" to "删除脚本",
        "scripts_delete_confirm" to "确定要删除脚本 [{name}] 吗？",
        "scripts_confirm_delete" to "确认删除",
        "scripts_imported_toast" to "成功导入本地脚本: {name}",
        "scripts_empty_content" to "脚本内容为空",
        "scripts_read_failed" to "读取脚本文件失败: {msg}",
        "scripts_close" to "关闭",
        "profile_override_title" to "配置覆写",
        "override_remote" to "远程订阅配置",
        "override_local" to "本地配置文件",
        "override_desc" to "开启后，此配置将由选中的脚本进行动态规则与策略组复写。",
        "override_go_scripts" to "前往脚本管理",
        "override_scripts_hint" to "导入、新建或编辑脚本代码",
        "override_select_scripts" to "选择要绑定的脚本",
        "override_no_scripts" to "当前尚无任何脚本\n请点击上方“前往脚本管理”导入脚本",
        "override_saved" to "配置覆写已保存",
        "override_save" to "保存覆写设置",
        "tile_connected" to "已连接",
        "tile_connecting" to "连接中…",
        "tile_disconnecting" to "断开中…",
        "tile_disconnected" to "已断开"
    )

    private val enExtra = mapOf(
        "back" to "Back",
        "logs_title" to "Core Live Logs",
        "logs_count" to "{n} records",
        "logs_copied" to "Logs copied to clipboard",
        "logs_copy" to "Copy logs",
        "logs_export" to "Export logs",
        "logs_clear" to "Clear logs",
        "logs_empty" to "No logs yet\nOnce the VPN is connected, the Mihomo core output will appear here",
        "log_level_all" to "All",
        "log_level_info" to "Info",
        "log_level_warning" to "Warning",
        "log_level_error" to "Error",
        "log_level_debug" to "Debug",
        "app_routing_title" to "Per-App Routing",
        "per_app_disabled" to "Off",
        "per_app_whitelist" to "Proxy selected",
        "per_app_blacklist" to "Bypass selected",
        "app_search_placeholder" to "Search app name or package…",
        "app_selected_count" to "{n} apps selected",
        "app_show_system" to "Show system apps",
        "app_proxied_section" to "Proxied apps ({n})",
        "app_unproxied_section" to "Bypassed apps ({n})",
        "app_no_match" to "No matching apps",
        "app_routing_disabled_hint" to "Per-app routing is off\nAll app traffic is routed by the Mihomo rules",
        "scripts_title" to "Scripts",
        "scripts_import_network" to "Import from URL",
        "scripts_import_local" to "Import local",
        "scripts_new" to "New script",
        "scripts_empty" to "No rewrite scripts yet\nUse the buttons above to import or create one",
        "scripts_bind_hint" to "Bind it in Profile Override to take effect",
        "scripts_edit" to "Edit",
        "scripts_new_title" to "New config script",
        "scripts_name_label" to "Script name",
        "scripts_name_placeholder" to "e.g. Clash_rule",
        "scripts_created" to "Script created",
        "scripts_create" to "Create",
        "scripts_import_url_title" to "Import script from URL",
        "scripts_name_optional" to "Script name (optional)",
        "scripts_url_label" to "Script URL",
        "scripts_downloaded" to "Script downloaded",
        "scripts_download_failed" to "Download failed: {msg}",
        "scripts_downloading" to "Downloading…",
        "scripts_import" to "Import",
        "scripts_edit_title" to "Edit: {name}",
        "scripts_saved" to "Script saved",
        "scripts_save_code" to "Save code",
        "scripts_delete_title" to "Delete script",
        "scripts_delete_confirm" to "Delete script [{name}]?",
        "scripts_confirm_delete" to "Confirm delete",
        "scripts_imported_toast" to "Imported local script: {name}",
        "scripts_empty_content" to "Script content is empty",
        "scripts_read_failed" to "Failed to read script file: {msg}",
        "scripts_close" to "Close",
        "profile_override_title" to "Profile Override",
        "override_remote" to "Remote subscription",
        "override_local" to "Local config file",
        "override_desc" to "When enabled, the selected scripts rewrite this profile's rules and proxy groups.",
        "override_go_scripts" to "Manage scripts",
        "override_scripts_hint" to "Import, create or edit script code",
        "override_select_scripts" to "Select scripts to bind",
        "override_no_scripts" to "No scripts yet\nTap \"Manage scripts\" above to import one",
        "override_saved" to "Override settings saved",
        "override_save" to "Save override settings",
        "tile_connected" to "Connected",
        "tile_connecting" to "Connecting…",
        "tile_disconnecting" to "Disconnecting…",
        "tile_disconnected" to "Disconnected"
    )

    private val ruExtra = mapOf(
        "back" to "Назад",
        "logs_title" to "Живой журнал ядра",
        "logs_count" to "Записей: {n}",
        "logs_copied" to "Журнал скопирован в буфер обмена",
        "logs_copy" to "Копировать журнал",
        "logs_export" to "Экспорт журнала",
        "logs_clear" to "Очистить журнал",
        "logs_empty" to "Журналов пока нет\nПосле подключения VPN вывод ядра Mihomo появится здесь",
        "log_level_all" to "Все",
        "log_level_info" to "Информация",
        "log_level_warning" to "Предупреждение",
        "log_level_error" to "Ошибка",
        "log_level_debug" to "Отладка",
        "app_routing_title" to "По приложениям",
        "per_app_disabled" to "Выкл.",
        "per_app_whitelist" to "Только выбранные",
        "per_app_blacklist" to "Обходить выбранные",
        "app_search_placeholder" to "Поиск по имени или пакету…",
        "app_selected_count" to "Выбрано приложений: {n}",
        "app_show_system" to "Показывать системные",
        "app_proxied_section" to "Проксируемые ({n})",
        "app_unproxied_section" to "Не проксируемые ({n})",
        "app_no_match" to "Приложения не найдены",
        "app_routing_disabled_hint" to "Разделение по приложениям выключено\nВесь трафик идёт по правилам Mihomo",
        "scripts_title" to "Скрипты",
        "scripts_import_network" to "Импорт по ссылке",
        "scripts_import_local" to "Локальный импорт",
        "scripts_new" to "Новый скрипт",
        "scripts_empty" to "Скриптов перезаписи нет\nИмпортируйте или создайте скрипт кнопками выше",
        "scripts_bind_hint" to "Включите его в переопределении профиля",
        "scripts_edit" to "Изменить",
        "scripts_new_title" to "Новый скрипт конфигурации",
        "scripts_name_label" to "Имя скрипта",
        "scripts_name_placeholder" to "напр. Clash_rule",
        "scripts_created" to "Скрипт создан",
        "scripts_create" to "Создать",
        "scripts_import_url_title" to "Импорт скрипта по ссылке",
        "scripts_name_optional" to "Имя скрипта (необязательно)",
        "scripts_url_label" to "URL скрипта",
        "scripts_downloaded" to "Скрипт загружен",
        "scripts_download_failed" to "Ошибка загрузки: {msg}",
        "scripts_downloading" to "Загрузка…",
        "scripts_import" to "Импорт",
        "scripts_edit_title" to "Изменить: {name}",
        "scripts_saved" to "Скрипт сохранён",
        "scripts_save_code" to "Сохранить код",
        "scripts_delete_title" to "Удалить скрипт",
        "scripts_delete_confirm" to "Удалить скрипт [{name}]?",
        "scripts_confirm_delete" to "Удалить",
        "scripts_imported_toast" to "Локальный скрипт импортирован: {name}",
        "scripts_empty_content" to "Содержимое скрипта пусто",
        "scripts_read_failed" to "Не удалось прочитать файл скрипта: {msg}",
        "scripts_close" to "Закрыть",
        "profile_override_title" to "Переопределение профиля",
        "override_remote" to "Удалённая подписка",
        "override_local" to "Локальный файл конфигурации",
        "override_desc" to "Если включено, выбранные скрипты перезапишут правила и группы этого профиля.",
        "override_go_scripts" to "Управление скриптами",
        "override_scripts_hint" to "Импорт, создание и правка скриптов",
        "override_select_scripts" to "Выберите скрипты",
        "override_no_scripts" to "Скриптов пока нет\nНажмите «Управление скриптами» выше",
        "override_saved" to "Переопределение сохранено",
        "override_save" to "Сохранить настройки",
        "tile_connected" to "Подключено",
        "tile_connecting" to "Подключение…",
        "tile_disconnecting" to "Отключение…",
        "tile_disconnected" to "Отключено"
    )

    private val zhAll = zh + zhExtra
    private val enAll = en + enExtra
    private val ruAll = ru + ruExtra

    fun get(key: String, languageCode: String = "SYSTEM"): String {
        val effectiveLang = if (languageCode == "SYSTEM") {
            val sys = Locale.getDefault().language
            if (sys == "zh" || sys == "ru") sys else "en"
        } else {
            languageCode
        }

        val dict = when (effectiveLang.lowercase()) {
            "zh" -> zhAll
            "ru" -> ruAll
            else -> enAll
        }

        return dict[key] ?: zhAll[key] ?: key
    }

    @Composable
    fun current(key: String): String {
        return get(key, LocalAppLanguage.current)
    }
}